name: pymllm macOS Nightly

on:
  pull_request:
    branches:
      - v2
    paths:
      - "pymllm/nightly.ini"
      - ".github/workflows/pymllm-macos-nightly.yml"
  push:
    branches:
      - v2
    paths:
      - "pymllm/nightly.ini"
      - ".github/workflows/pymllm-macos-nightly.yml"

jobs:
  build-and-publish:
    if: github.repository == 'UbiquitousLearning/mllm'
    runs-on: macos-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build
        run: |
          python -m pip install --upgrade pip

      - name: Set nightly version
        run: |
          NIGHTLY_VERSION="0.1.0.dev$(date +%Y%m%d)"
          sed -i '' -E 's/^version = "[^"]+"/version = "'$NIGHTLY_VERSION'"/' pyproject.toml

      - name: Build wheel
        run: |
          python -m build --wheel --outdir wheelhouse .

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: wheelhouse/
