name: pymllm macOS Nightly

on:
  pull_request:
    branches:
      - v2
    paths:
      - "pymllm/nightly.ini"
      - ".github/workflows/pymllm-macos-nightly.yml"
  push:
    branches:
      - v2
    paths:
      - "pymllm/nightly.ini"
      - ".github/workflows/pymllm-macos-nightly.yml"

jobs:
  build:
    if: github.repository == 'UbiquitousLearning/mllm'
    runs-on: macos-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --init --recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compute next beta version
        id: beta
        run: |
          BASE_VER=$(grep -m1 '^version\s*=' pyproject.toml \
                    | sed -E 's/^version\s*=\s*"([0-9]+\.[0-9]+\.[0-9]+).*/\1/')

          LAST_B=$(pip index versions pymllm 2>/dev/null \
                  | grep -oP "${BASE_VER//./\\.}b\K[0-9]+" \
                  | head -1 || true)

          if [[ -z "$LAST_B" ]]; then
            NEXT_B=0
          else
            NEXT_B=$((LAST_B + 1))
          fi

          NEXT_VER="${BASE_VER}b${NEXT_B}"
          echo "version=$NEXT_VER" >> $GITHUB_OUTPUT
          echo "Next beta version => $NEXT_VER"

      - name: Bump to next beta
        run: |
          sed -i.bak -E 's/^version\s*=.*/version = "${{ steps.beta.outputs.version }}"/' pyproject.toml

      - name: Build wheel
        run: |
          pip wheel -v -w dist .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-packages
          path: dist/
          retention-days: 1

  publish:
    if: github.repository == 'UbiquitousLearning/mllm'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-packages
          path: dist/

      - name: Remove non-pymllm packages
        run: |
          find dist -type f \! -name '*pymllm*' -delete
          ls -l dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
